### ISSUE TITLE
能更新到最新版本的LVGL吗？

### ISSUE THREAD

**Issue by Leadrive** [Leadiffer/lvgl_cpp_v6x#1]
谢谢！

**Comment by ShenRen** [comment]
由于最新的稳定版本lvgl 7.11.x 相对于lvgl 6.x 变动比较大，我们采用了新的方式进行C++封装。不会在这个基础上进行升级。但是这个版本我们也在一直维护，并应用到了自家的产品中。有什么使用问题的话可以和我联系。

**Comment by ShenRen** [comment]
想要对新版本的lvgl 7.x 进行封装，可以参考我在 https://github.com/Leadiffer/lvgl_6x 中的代码修改记录，将它移植到lvgl 7.x中

**Comment by Leadrive** [comment]
好的，谢谢。还要熟悉一段时间，项目比较紧。
